export const ADD_PROMOTION_INITIATED = 'ADD_PROMOTION_INITIATED'
export const ADD_PROMOTION_SUCCESS = 'ADD_PROMOTION_SUCCESS'
export const ADD_PROMOTION_FAILED = 'ADD_PROMOTION_FAILED'

export const UPDATE_PROMOTION_INITIATED = 'UPDATE_PROMOTION_INITIATED'
export const UPDATE_PROMOTION_SUCCESS = 'UPDATE_PROMOTION_SUCCESS'
export const UPDATE_PROMOTION_FAILED = 'UPDATE_PROMOTION_FAILED'

export const DELETE_PROMOTION_INITIATED = 'DELETE_PROMOTION_INITIATED'
export const DELETE_PROMOTION_SUCCESS = 'DELETE_PROMOTION_SUCCESS'
export const DELETE_PROMOTION_FAILED = 'DELETE_PROMOTION_FAILED'

export const GET_PROMOTION_LIST_INITIATED = 'GET_PROMOTION_LIST_INITIATED'
export const GET_PROMOTION_LIST_SUCCESS = 'GET_PROMOTION_LIST_SUCCESS'
export const GET_PROMOTION_LIST_FAILED = 'GET_PROMOTION_LIST_FAILED'

export const SELECT_CHANGE = 'SELECT_CHANGE'
export const PAGE_CHANGE = 'PAGE_CHANGE'

export const RESET_PROMOTION_STATES = 'RESET_PROMOTION_STATES'
