export const LOGIN_INITIATED = 'LOGIN_INITIATED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL'

export const INITIATE_REGISTRATION = 'REGISTRATION_INITIATED'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED'
export const RESET_REGISTRATION_STATE = 'RESET_REGISTRATION_STATE'

export const FETCH_PROFILE_INITIATED = 'FETCH_PROFILE_INITIATED'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILED = 'FETCH_PROFILE_FAILED'

export const UPDATE_PROFILE_INITIATED = 'UPDATE_PROFILE_INITIATED'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'
export const RESET_PROFILE_UPDATE_STATE = 'RESET_PROFILE_UPDATE_STATE'

export const UPDATE_ADMIN_PASSWORD_INITIATED = 'UPDATE_ADMIN_PASSWORD_INITIATED'
export const UPDATE_ADMIN_PASSWORD_SUCCESS = 'UPDATE_ADMIN_PASSWORD_SUCCESS'
export const UPDATE_ADMIN_PASSWORD_FAILED = 'UPDATE_ADMIN_PASSWORD_FAILED'
export const RESET_ADMIN_PASSWORD_UPDATE_STATE = 'RESET_ADMIN_PASSWORD_UPDATE_STATE'

export const FETCH_ADMIN_INITIATED = 'FETCH_ADMIN_INITIATED'
export const FETCH_ADMIN_SUCCESS = 'FETCH_ADMIN_SUCCESS'
export const FETCH_ADMIN_FAILED = 'FETCH_ADMIN_FAILED'

export const UPDATE_ADMIN_INITIATED = 'UPDATE_ADMIN_INITIATED'
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS'
export const UPDATE_ADMIN_FAILED = 'UPDATE_ADMIN_FAILED'
export const RESET_ADMIN_UPDATE_STATE = 'RESET_ADMIN_UPDATE_STATE'

export const DELETE_ADMIN_INITIATED = 'DELETE_ADMIN_INITIATED'
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS'
export const DELETE_ADMIN_FAILED = 'DELETE_ADMIN_FAILED'

export const FETCH_ADMINS_INITIATED = 'FETCH_ADMINS_INITIATED'
export const FETCH_ADMINS_FAILED = 'FETCH_ADMINS_FAILED'
export const FETCH_ADMINS_SUCCESS = 'FETCH_ADMINS_SUCCESS'
export const RESET_ADMINS_LIST = 'RESET_ADMINS_LIST'

export const SELECT_CHANGE = 'SELECT_CHANGE'
export const PAGE_CHANGE = 'PAGE_CHANGE'
