export const RESET_UPDATE_AD_SETTINGS = 'RESET_UPDATE_AD_SETTINGS'

export const GET_SETTINGS_INITIATE = 'GET_SETTINGS_INITIATE'
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS'
export const GET_SETTINGS_FAILURE = 'GET_SETTINGS_FAILURE'

export const UPDATE_AD_SETTINGS_INITIATE = 'UPDATE_AD_SETTINGS_INITIATE'
export const UPDATE_AD_SETTINGS_SUCCESS = 'UPDATE_AD_SETTINGS_SUCCESS'
export const UPDATE_AD_SETTINGS_FAILURE = 'UPDATE_AD_SETTINGS_FAILURE'

export const IN_APP_UPDATE_SETTINGS_INITIATE = 'IN_APP_UPDATE_SETTINGS_INITIATE'
export const IN_APP_UPDATE_SETTINGS_SUCCESS = 'IN_APP_UPDATE_SETTINGS_SUCCESS'
export const IN_APP_UPDATE_SETTINGS_FAILURE = 'IN_APP_UPDATE_SETTINGS_FAILURE'
