export const SEND_PUSH_NOTIFICATION_INITIATED = 'SEND_PUSH_NOTIFICATION_INITIATED'
export const SEND_PUSH_NOTIFICATION_SUCCESS = 'SEND_PUSH_NOTIFICATION_SUCCESS'
export const SEND_PUSH_NOTIFICATION_FAILURE = 'SEND_PUSH_NOTIFICATION_FAILURE'

export const RESEND_NOTIFICATION_INITIATED = 'RESEND_NOTIFICATION_INITIATED'
export const RESEND_NOTIFICATION_SUCCESS = 'RESEND_NOTIFICATION_SUCCESS'
export const RESEND_NOTIFICATION_FAILURE = 'RESEND_NOTIFICATION_FAILURE'
export const REST_PUSH_NOTIFICATION_STATE = 'REST_PUSH_NOTIFICATION_STATE'

export const DELETE_PUSH_NOTIFICATION_INITIATED = 'DELETE_PUSH_NOTIFICATION_INITIATED'
export const DELETE_PUSH_NOTIFICATION_SUCCESS = 'DELETE_PUSH_NOTIFICATION_SUCCESS'
export const DELETE_PUSH_NOTIFICATION_FAILURE = 'DELETE_PUSH_NOTIFICATION_FAILURE'
export const REST_DELETE_PUSH_NOTIFICATION_STATE = 'REST_DELETE_PUSH_NOTIFICATION_STATE'

export const LIST_NOTIFICATIONS_INITIATED = 'LIST_NOTIFICATIONS_INITIATED'
export const LIST_NOTIFICATIONS_SUCCESS = 'LIST_NOTIFICATIONS_SUCCESS'
export const LIST_NOTIFICATIONS_FAILURE = 'LIST_NOTIFICATIONS_FAILURE'
export const REST_LIST_NOTIFICATIONS_STATE = 'REST_LIST_NOTIFICATIONS_STATE'

export const PAGE_CHANGE = 'PAGE_CHANGE'
export const SELECT_CHANGE = 'SELECT_CHANGE'
