export const REGISTER_APP_INITIATED = 'REGISTER_APP_INITIATED'
export const REGISTER_APP_SUCCESS = 'REGISTER_APP_SUCCESS'
export const REGISTER_APP_FAILED = 'REGISTER_APP_FAILED'

export const UPDATE_APP_INITIATED = 'UPDATE_APP_INITIATED'
export const UPDATE_APP_SUCCESS = 'UPDATE_APP_SUCCESS'
export const UPDATE_APP_FAILED = 'UPDATE_APP_FAILED'

export const DELETE_APP_INITIATED = 'DELETE_APP_INITIATED'
export const DELETE_APP_SUCCESS = 'DELETE_APP_SUCCESS'
export const DELETE_APP_FAILED = 'DELETE_APP_FAILED'

export const FETCH_APP_INITIATED = 'FETCH_APP_INITIATED'
export const FETCH_APP_SUCCESS = 'FETCH_APP_SUCCESS'
export const FETCH_APP_FAILED = 'FETCH_APP_FAILED'

export const GET_APP_LIST_INITIATED = 'GET_APP_LIST_INITIATED'
export const GET_APP_LIST_SUCCESS = 'GET_APP_LIST_SUCCESS'
export const GET_APP_LIST_FAILED = 'GET_APP_LIST_FAILED'

export const SELECT_CHANGE = 'SELECT_CHANGE'
export const PAGE_CHANGE = 'PAGE_CHANGE'

export const RESET_APP_STATES = 'RESET_APP_STATES'
